name: Build LabyAddon

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🔥 Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 🔑 Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔨 Build with Gradle
        run: ./gradlew build --full-stacktrace